version: "3.2"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:4200
#    Dev Mode Start
#    volumes:
#      - ./client:/client
#      - /client/node_modules
#    Dev Mode End
    restart: always
    container_name: ims_client
    networks:
      - ims-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4201:4201
    container_name: ims_server
    networks:
      - ims-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ims-mysql:/var/lib/mysql
    restart: always
    container_name: ims_mysql
    networks:
      - ims-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ims_mysql

  adminer:
    image: adminer
    ports:
      - 9001:8080
    restart: always
    container_name: ims_adminer
    networks:
      - ims-network

volumes:
  ims-mysql:

networks:
  ims-network:
